openapi: 3.0.3
info:
  title: Employees API
  description: The full description of the _Employees API_.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: Local development environment
paths:
  /api/employees:
    get:
      summary: List employees
      description: The full description of list employees operation
      operationId: listEmployees
      tags:
        - employees
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  title: Employee
                  properties:
                    id:
                      type: integer
                      format: int64
                      description: The id of the employee
                    name:
                      type: string
                      description: The name of the employee
                example:
                  - id: 1
                    name: John Doe
                  - id: 2
                    name: Jane Doe